[package]
name = "yatta"
about = "Yet Another Time Tracking App"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
directories = "5.0.1"
rusqlite = { version = "0.31.0", features = ["bundled"]}
